import { z } from 'zod';
import type { Channel } from '../shared/api';
import { TRANSACTION_TYPES, CATEGORY_KINDS, ASSET_TYPES, ACCOUNT_KINDS, HOUSEHOLDS, HOUSINGS, INCOME_STABILITIES, LIFE_GOALS } from '../shared/types';

const id = z.number().int().positive();
const month = z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/, 'Mes con formato AAAA-MM');
const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Fecha con formato AAAA-MM-DD');
const cents = z.number().int().refine(Number.isSafeInteger);
const color = z.string().regex(/^#[0-9a-fA-F]{6}$/);
const text = (max: number) => z.string().max(max);
const none = z.undefined().or(z.null()).optional();
const txType = z.enum(TRANSACTION_TYPES);
const kind = z.enum(CATEGORY_KINDS);
const symbol = z.string().regex(/^[A-Za-z0-9.\-=^]{1,24}$/, 'Símbolo no válido');

const detection = z.object({
  senderDomains: z.array(z.string().trim().toLowerCase().regex(/^[a-z0-9.-]+\.[a-z]{2,}$/, 'Dominio no válido')).max(30),
  senderAddresses: z.array(z.string().trim().toLowerCase().email()).max(30),
  subjectKeywords: z.array(text(60)).max(40),
  filenameKeywords: z.array(text(60)).max(40),
  minScore: z.number().int().min(35).max(100),
}).partial();

const settingsPatch = z.object({
  theme: z.enum(['system', 'light', 'dark']),
  keepDocuments: z.boolean(),
  incomeMode: z.enum(['auto', 'manual', 'documents', 'combined']),
  initialLookbackMonths: z.number().int().min(1).max(60),
  autoSyncOnStart: z.boolean(),
  onboardingCompleted: z.boolean(),
  detection,
  marketDataEnabled: z.boolean(),
  autoUpdate: z.boolean(),
  lastSeenVersion: z.string().regex(/^\d{1,4}\.\d{1,4}\.\d{1,4}$/).nullable(),
  notifications: z.object({
    enabled: z.boolean(),
    email: z.boolean(),
    emailAmounts: z.boolean(),
    weeklySummary: z.boolean(),
    lowBalanceCents: cents.min(0).max(100000000),
  }).partial().strict(),
  desktop: z.object({ trayOnClose: z.boolean(), openAtLogin: z.boolean() }).partial().strict(),
  syncIntervalHours: z.number().int().min(0).max(48),
  principalAsSavings: z.boolean(),
  stocks: z.object({
    stopLossPct: z.number().min(1).max(90),
    trailingStopPct: z.number().min(1).max(90),
    takeProfitPct: z.number().min(1).max(1000),
    dipPct: z.number().min(1).max(90),
    maxPositionPct: z.number().min(1).max(100),
    notify: z.boolean(),
  }).partial().strict(),
  profile: z.object({
    ownerNames: z.array(z.string().trim().min(3).max(80)).max(5),
    household: z.enum(HOUSEHOLDS).nullable(),
    partnerName: z.string().trim().max(80).nullable(),
    dependents: z.number().int().min(0).max(20),
    housing: z.enum(HOUSINGS).nullable(),
    incomeStability: z.enum(INCOME_STABILITIES).nullable(),
    priorityCategoryIds: z.array(z.number().int().positive()).max(30),
    goals: z.array(z.enum(LIFE_GOALS)).max(LIFE_GOALS.length),
  }).partial().strict(),
}).partial().strict();

const goal = z.object({
  mode: z.enum(['amount', 'percent']),
  amountCents: cents.min(0).nullable(),
  percentBp: z.number().int().min(0).max(10000).nullable(),
  effectiveFrom: month,
}).strict().refine((g) => (g.mode === 'amount' ? g.amountCents !== null : g.percentBp !== null), 'Falta el valor del objetivo');

/** Runtime validation of every renderer → main payload. Unknown keys are rejected. */
export const IPC_SCHEMAS: Record<Channel, z.ZodType> = {
  'app.info': none,
  'app.completeOnboarding': none,
  'profiles.list': none,
  'profiles.create': z.object({ name: text(40).trim().min(1), color, photo: z.string().max(400000).regex(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/).nullable() }).strict(),
  'profiles.update': z.object({ id: z.string().regex(/^[a-z0-9]{1,20}$/), name: text(40).trim().min(1).optional(), color: color.optional(), photo: z.string().max(400000).regex(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/).nullable().optional() }).strict(),
  'profiles.switch': z.object({ id: z.string().regex(/^[a-z0-9]{1,20}$/) }).strict(),
  'profiles.setAskOnStart': z.object({ value: z.boolean() }).strict(),
  'profiles.delete': z.object({ id: z.string().regex(/^[a-z0-9]{1,20}$/) }).strict(),
  'settings.get': none,
  'settings.update': settingsPatch,
  'categories.list': z.object({ from: isoDate.optional(), to: isoDate.optional() }).strict().optional().nullable(),
  'categories.create': z.object({ name: text(40).trim().min(1), kind, color }).strict(),
  'categories.update': z.object({ id, name: text(40).trim().min(1).optional(), kind: kind.optional(), color: color.optional() }).strict(),
  'categories.delete': z.object({ id }).strict(),
  'transactions.list': z.object({
    search: text(100).optional(),
    categoryId: id.optional(),
    type: txType.optional(),
    from: isoDate.optional(),
    to: isoDate.optional(),
    merchantId: id.optional(),
    accountId: id.optional(),
    includeExcluded: z.boolean().optional(),
    onlyExcluded: z.boolean().optional(),
    uncategorizedOnly: z.boolean().optional(),
    sort: z.enum(['date', 'amount', 'merchant', 'category']).optional(),
    dir: z.enum(['asc', 'desc']).optional(),
    limit: z.number().int().min(1).max(500).optional(),
    offset: z.number().int().min(0).optional(),
  }).strict(),
  'transactions.get': z.object({ id }).strict(),
  'transactions.update': z.object({
    id,
    categoryId: id.optional(),
    merchantName: text(120).optional(),
    type: txType.optional(),
    isExcluded: z.boolean().optional(),
    notes: text(2000).nullable().optional(),
  }).strict(),
  'rules.list': none,
  'rules.create': z.object({ matchType: z.enum(['merchant', 'contains']), pattern: text(120).min(1), categoryId: id, applyToExisting: z.boolean() }).strict(),
  'rules.delete': z.object({ id }).strict(),
  'merchants.rename': z.object({ merchantId: id, name: text(120).trim().min(1) }).strict(),
  'recurring.list': none,
  'recurring.setStatus': z.object({ id, status: z.enum(['probable', 'confirmed', 'dismissed']) }).strict(),
  'recurring.redetect': none,
  'income.list': none,
  'income.save': z.object({
    id: id.optional(),
    kind: z.enum(['salary', 'recurring', 'extraordinary']),
    label: text(80).trim().min(1),
    amountCents: cents.min(0).max(100_000_000_00),
    startMonth: month,
    endMonth: month.nullable(),
  }).strict().refine((i) => i.endMonth === null || i.endMonth >= i.startMonth, 'El mes final debe ser posterior al inicial'),
  'income.delete': z.object({ id }).strict(),
  'goal.get': none,
  'goal.set': goal.nullable(),
  'analytics.dashboard': z.object({ month: month.optional() }).strict().optional().nullable(),
  'analytics.report': z.object({ from: month, to: month }).strict(),
  'analytics.savings': z.object({ month: month.optional() }).strict().optional().nullable(),
  'recommendations.list': none,
  'recommendations.dismiss': z.object({ key: text(200).min(1) }).strict(),
  'import.pickAndImport': none,
  'import.withPassword': z.object({ token: z.string().uuid(), password: z.string().min(1).max(256), remember: z.boolean().optional() }).strict(),
  'import.forgetPasswords': none,
  'import.documents': none,
  'import.review': z.object({ documentId: id }).strict(),
  'import.reviewSummary': none,
  'import.updateReviewItem': z.object({
    id,
    date: isoDate.optional(),
    description: text(300).optional(),
    amountCents: cents.optional(),
    type: txType.optional(),
    status: z.enum(['pending', 'accepted', 'discarded']).optional(),
  }).strict(),
  'import.confirmReview': z.object({ documentId: id }).strict(),
  'import.discardDocument': z.object({ documentId: id }).strict(),
  'import.openDocument': z.object({ documentId: id }).strict(),
  'import.deleteRetainedDocuments': none,
  'email.status': none,
  'email.saveClientConfig': z.object({
    clientId: z.string().trim().regex(/^[\w-]+\.apps\.googleusercontent\.com$/, 'El ID de cliente debe terminar en .apps.googleusercontent.com'),
    clientSecret: z.string().trim().min(8).max(200),
  }).strict(),
  'email.clearClientConfig': none,
  'email.connect': z.object({ send: z.boolean().optional() }).strict().optional().nullable(),
  'email.disconnect': none,
  'email.scan': z.object({ lookbackMonths: z.number().int().min(1).max(60).optional() }).strict().optional().nullable(),
  'email.importSelected': z.object({ messageIds: z.array(z.string().regex(/^[\w-]{6,64}$/)).min(1).max(300) }).strict(),
  'email.syncNow': none,
  'email.retryPassword': z.object({ messageId: z.string().regex(/^[\w-]{6,64}$/), password: z.string().min(1).max(256) }).strict(),
  'email.pendingPasswords': none,
  'email.unlockPending': z.object({ password: z.string().min(1).max(256), remember: z.boolean() }).strict(),
  'data.info': none,
  'data.exportTransactions': z.object({ format: z.enum(['csv', 'json']) }).strict(),
  'data.backup': none,
  'data.restore': z.object({ confirmation: z.string().max(40) }).strict(),
  'data.deleteAll': z.object({ confirmation: z.string().max(40) }).strict(),
  'data.loadDemo': none,
  'data.removeDemo': none,
  'accounts.list': none,
  'budgets.overview': z.object({ month: month.optional() }).strict().or(none),
  'budgets.set': z.object({ categoryId: id, amountCents: cents.min(0).max(100000000).nullable() }).strict(),
  'alerts.list': none,
  'alerts.markRead': z.object({ key: text(300).optional() }).strict().or(none),
  'lock.status': none,
  'lock.unlockPin': z.object({ pin: z.string().regex(/^\d{1,12}$/) }).strict(),
  'lock.unlockHello': none,
  'lock.lockNow': none,
  'lock.configure': z.object({
    enabled: z.boolean().optional(),
    windowsHello: z.boolean().optional(),
    autoLockMinutes: z.number().int().min(0).max(240).optional(),
    pin: z.string().regex(/^\d{4,8}$/, 'El PIN debe tener entre 4 y 8 cifras').optional(),
    currentPin: z.string().regex(/^\d{1,12}$/).optional(),
  }).strict(),
  'accounts.update': z.object({ id, name: text(80).trim().min(1).optional(), kind: z.enum(ACCOUNT_KINDS).optional(), includeInNetWorth: z.boolean().optional(), annualRateBp: z.number().int().gt(-10000).lt(100000).nullable().optional(), ownTransferTarget: z.boolean().optional() }).strict(),
  'accounts.setBalance': z.object({ id, balanceCents: cents, date: isoDate }).strict(),
  'accounts.createManual': z.object({ name: text(80).trim().min(1), bank: text(80), kind: z.enum(ACCOUNT_KINDS), balanceCents: cents, date: isoDate, annualRateBp: z.number().int().gt(-10000).lt(100000).nullable(), ownTransferTarget: z.boolean() }).strict(),
  'accounts.merge': z.object({ fromId: id, intoId: id }).strict(),
  'accounts.deleteManual': z.object({ id }).strict(),
  'accounts.counterparties': none,
  'accounts.extraordinary': none,
  'accounts.resolveExtraordinary': z.object({ id, asCapital: z.boolean() }).strict(),
  'accounts.decideCounterparty': z.object({ key: text(200).min(1), displayName: text(120).optional(), role: z.enum(['own', 'partner', 'other']).nullable(), accountId: id.nullable(), categoryId: id.nullable() }).strict(),
  'app.updateStatus': none,
  'app.checkUpdates': none,
  'app.installUpdate': none,
  'data.clearImported': z.object({ confirmation: z.string().max(40) }).strict(),
  'data.openDataDir': none,
  'pots.overview': none,
  'pots.save': z.object({
    id: id.optional(),
    name: text(60).trim().min(1),
    kind: z.enum(['goal', 'emergency']),
    targetCents: cents.min(1).max(1_000_000_000_00),
    targetDate: isoDate.nullable(),
    color,
  }).strict(),
  'pots.delete': z.object({ id }).strict(),
  'pots.movements': z.object({ potId: id }).strict(),
  'pots.addMovement': z.object({ potId: id, date: isoDate, amountCents: cents.refine((v) => v !== 0, 'El importe no puede ser cero'), note: text(200).nullable() }).strict(),
  'pots.deleteMovement': z.object({ id }).strict(),
  'wealth.overview': none,
  'wealth.saveAsset': z.object({
    id: id.optional(),
    name: text(80).trim().min(1),
    type: z.enum(ASSET_TYPES),
    institution: text(80).nullable(),
    notes: text(500).nullable(),
    mode: z.enum(['manual', 'rate', 'loan']).optional(),
    annualRateBp: z.number().int().gt(-10000).lt(100000).nullable().optional(),
    monthlyContributionCents: cents.min(0).nullable().optional(),
    symbol: z.string().regex(/^[A-Za-z0-9.\-=^]{1,24}$/).nullable().optional(),
    rateSource: text(200).nullable().optional(),
    principalCents: cents.min(1).nullable().optional(),
    termMonths: z.number().int().min(1).max(600).nullable().optional(),
    startDate: isoDate.nullable().optional(),
  }).strict(),
  'wealth.loanSchedule': z.object({ assetId: id }).strict(),
  'wealth.earlyRepayment': z.object({ assetId: id, date: isoDate, amountCents: cents.min(1), strategy: z.enum(['reduce_term', 'reduce_payment']) }).strict(),
  'market.search': z.object({ query: text(60).trim().min(2) }).strict(),
  'market.returns': z.object({ symbol: z.string().regex(/^[A-Za-z0-9.\-=^]{1,24}$/) }).strict(),
  'forecast.overview': none,
  'budgets.setMany': z.object({ items: z.array(z.object({ categoryId: id, amountCents: cents.min(1) }).strict()).min(1).max(40) }).strict(),
  'assistant.ask': z.object({ question: text(300) }).strict(),
  'notify.testEmail': none,
  'data.audit': none,
  'stocks.overview': none,
  'stocks.refresh': z.object({ force: z.boolean().optional() }).strict().optional().nullable(),
  'stocks.addWatch': z.object({ symbol }).strict(),
  'stocks.removeWatch': z.object({ symbol }).strict(),
  'stocks.setTarget': z.object({ symbol, targetPrice: z.number().positive().max(1e9).nullable() }).strict(),
  'stocks.addTrade': z.object({
    symbol,
    side: z.enum(['buy', 'sell']),
    date: isoDate,
    quantity: z.number().positive().max(1e9),
    price: z.number().positive().max(1e9),
    currency: z.string().regex(/^[A-Za-z]{3}$/, 'Moneda de 3 letras (EUR, USD…)'),
    fxPerEur: z.number().positive().max(1e6).nullable(),
    feesCents: cents.min(0),
    note: text(200).nullable(),
  }).strict(),
  'stocks.deleteTrade': z.object({ id }).strict(),
  'wealth.deleteAsset': z.object({ id }).strict(),
  'wealth.valuations': z.object({ assetId: id }).strict(),
  'wealth.saveValuation': z.object({ assetId: id, date: isoDate, valueCents: cents.min(0), contributedCents: cents.min(0).nullable(), note: text(200).nullable() }).strict(),
  'wealth.deleteValuation': z.object({ id }).strict(),
  'shell.openHelp': z.object({ topic: z.enum(['google-cloud-console', 'gmail-api', 'oauth-consent']) }).strict(),
};
